CREATE TABLE IF NOT EXISTS BATCH_JOB_EXECUTION
(
  BATCH_JOB_ID          VARCHAR(128) NOT NULL PRIMARY KEY,
  JOB_TYPE              VARCHAR(128),
  JOB_EXECUTION_RESULTS TEXT,
  EXECUTION_STATUS      VARCHAR(20),
  START_TIME        DATETIME DEFAULT NULL,
  END_TIME          DATETIME DEFAULT NULL
);

CREATE TABLE IF NOT EXISTS JOB_EXECUTION
(
  JOB_ID            VARCHAR(256) NOT NULL PRIMARY KEY,
  BATCH_JOB_ID      VARCHAR(128),
  START_TIME        DATETIME DEFAULT NULL,
  UPDATE_TIME        DATETIME DEFAULT NULL,
  END_TIME          DATETIME DEFAULT NULL,
  EXECUTION_STATUS  VARCHAR(20),
  EXECUTION_CONTEXT TEXT,
  MESSAGE           TEXT
);

CREATE TABLE IF NOT EXISTS STEP_EXECUTION
(
  STEP_ID           VARCHAR(512) NOT NULL PRIMARY KEY,
  STEP_NAME         VARCHAR(50) NOT NULL,
  JOB_ID            VARCHAR(128) NOT NULL,
  START_TIME        DATETIME DEFAULT NULL,
  END_TIME          DATETIME DEFAULT NULL,
  EXECUTION_STATUS  VARCHAR(20),
  EXECUTION_CONTEXT TEXT,
  MESSAGE           TEXT,
  constraint JOB_EXEC_STEP_FK foreign key (JOB_ID)
  references JOB_EXECUTION (JOB_ID)
);
